apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../_base

components:
  - ../_components/linuxserver
  - ../_components/media-data

images:
  - name: app-image
    newName: lscr.io/linuxserver/sonarr
    newTag: latest

labels:
  - pairs:
      app: sonarr
    includeSelectors: true # also Deployment selector, pod labels, Service selector
  - pairs:
      type: media
    includeTemplates: false
    includeSelectors: false

patches:
  # rename Deployment, Service and Ingress from "app" to "radarr"
  - target:
      name: app
    patch: |-
      - op: replace
        path: /metadata/name
        value: sonarr
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 8989
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: app
      spec:
        template:
          spec:
            volumes:
              - name: config # matched by name, not position
                hostPath:
                  path: /home/ad/homelab/config/sonarr
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 8989
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: sonarr.h18s.lab
