apiVersion: v1
kind: ServiceAccount
metadata:
  name: toggler
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: toggler
  namespace: default
rules:
  # read status, and scale only these Deployments; keep in sync with APPS
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames:
      ["jellyfin", "prowlarr", "qbittorrent", "radarr", "seerr", "sonarr", "syncthing"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    resourceNames:
      ["jellyfin", "prowlarr", "qbittorrent", "radarr", "seerr", "sonarr", "syncthing"]
    verbs: ["patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: toggler
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: toggler
subjects:
  - kind: ServiceAccount
    name: toggler
    namespace: default
