apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../_base

components:
  - ../_components/linuxserver # no media-data: prowlarr only talks to indexers and the *arr apps

images:
  - name: app-image
    newName: lscr.io/linuxserver/prowlarr
    newTag: latest

labels:
  - pairs:
      app: prowlarr
    includeSelectors: true # also Deployment selector, pod labels, Service selector
  - pairs:
      type: media
    includeTemplates: false
    includeSelectors: false

patches:
  # rename Deployment, Service and Ingress from "app" to "prowlarr"
  - target:
      name: app
    patch: |-
      - op: replace
        path: /metadata/name
        value: prowlarr
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 9696
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/hostPath/path
        value: /home/ad/homelab/config/prowlarr
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 9696
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: prowlarr.h18s.lab
