# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  rules:
    - host: app.h18s.lab
      http:
        paths:
          - path: / # Match this path, Since this is /, it will match to everything with that host
            pathType: Prefix
            # If those match, where to go.. backend section
            backend:
              service:
                name: app
                port:
                  name: http
---
