apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ad1822/h18s.git
        revision: dev
        directories:
          - path: "*" # Wildcard tells Argo CD to scan every top-level directory
  template:
    metadata:
      name: "{{path.basename}}" # Creates apps named 'deployment', 'ingress', 'service', etc.
    spec:
      project: default
      source:
        repoURL: https://github.com/ad1822/h18s.git
        targetRevision: dev
        path: "{{path}}" # Automatically points to the discovered directory
      destination:
        server: https://kubernetes.default.svc
        namespace: default # Or '{{path.basename}}' if you want separate namespaces
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
