apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      type: sync
      tier: user-facing
    includeTemplates: false # Also apply labels in Pod
    includeSelectors: false # Don't apply labels in matchSelectors
