on:
  push:
    branches:
      - dev
      - main
    # paths:
    #   - "apps"
    #   - "argocd"
    #   - "infra"

jobs:
  validate-kubeconform:
    strategy:
      matrix:
        app-path:
          [
            "./apps/backup",
            "./apps/homepage",
            "./apps/jellyfin",
            "./apps/prowlarr",
            "./apps/qbittorrent",
            "./apps/radarr",
            "./apps/seerr",
            "./apps/sonarr",
            "./apps/syncthing",
            "./apps/toggler",
            "./argocd/apps",
            "./argocd/projects",
            "./infra/argocd",
            "./infra/sealed-secrets",
            "./infra/traefik",
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup kubeconform
        uses: bmuschko/setup-kubeconform@v1

      - name: Validate every kubernetes file
        run: |
          echo "Validating manifests inside: ${{ matrix.app-path }}"
          kubeconform -summary -strict -ignore-missing-schemas .
        working-directory: ${{ matrix.app-path }}
